import React, { useState } from 'react';
import { 
  Database, 
  Server, 
  Layers, 
  Palette, 
  Copy, 
  Check, 
  Download, 
  Shield, 
  Smartphone, 
  Activity,
  FolderGit2
} from 'lucide-react';
import { GitHubSyncModal } from './GitHubSyncModal';

export const TechSpecView: React.FC = () => {
  const [activeTab, setActiveTab] = useState<'database' | 'api' | 'architecture' | 'tokens' | 'healthkit'>('database');
  const [copied, setCopied] = useState(false);
  const [showGithubModal, setShowGithubModal] = useState(false);

  const fullMarkdownSpec = `# S-Trainer app — Plataforma de Entrenamiento
Arquitectura Full-Stack, Esquemas Relacionales, Endpoints API y Sistema de Diseño

## 1. Identidad de Marca y Sistema Visual
- Fondo primario: #101012
- Tarjetas y componentes: #1B1B1F, #232328, #16161A
- Bordes y divisores: #2A2A2F, #3A3A40
- Texto primario: #F5F4F0
- Texto secundario / deshabilitado: #8E8E94, #5C5C62
- Acento de marca (default): #CFFF5C (alternativas: #FF6B4A, #5CD6FF, #FFD34D)
- Codificación de color por tipo de dato:
  * Pasos: #FF6B4A (rojo/naranja)
  * Peso / Medidas: #5CD6FF (azul)
  * Sueño: #B388FF (púrpura)
  * Fuerza / Progreso: #CFFF5C (lima)
  * Nutrición: #CFFF5C (lima)
  * Ciclo menstrual: #E8A0C4 (rosa)
- Tipografías:
  * Títulos/Display: Bricolage Grotesque (peso 800)
  * Cuerpo/General: Manrope (pesos 400-800)
- Dimensiones:
  * App Móvil Cliente: 390px × 844px
  * Panel Web Entrenador: 1280px × 900px

## 2. Esquema Relacional de Base de Datos (PostgreSQL / Prisma)
\`\`\`prisma
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

enum Role {
  CLIENT
  TRAINER
  ADMIN
}

enum ClientStatus {
  ACTIVO
  PAUSADO
  PENDIENTE
}

enum MenstrualPhase {
  MENSTRUAL
  FOLICULAR
  OVULATORIA
  LUTEA
}

model User {
  id            String    @id @default(uuid())
  email         String    @unique
  passwordHash  String
  role          Role      @default(CLIENT)
  createdAt     DateTime  @default(now())
  updatedAt     DateTime  @updatedAt
  clientProfile Client?
  trainerProfile Trainer?
}

model Trainer {
  id          String         @id @default(uuid())
  userId      String         @unique
  user        User           @relation(fields: [userId], references: [id])
  name        String
  couponCode  String?        @default("STRAINER20")
  clients     Client[]
  programs    Program[]
  nutritionPlans NutritionPlan[]
  notes       TrainerNote[]
}

model Client {
  id                       String         @id @default(uuid())
  userId                   String         @unique
  user                     User           @relation(fields: [userId], references: [id])
  trainerId                String
  trainer                  Trainer        @relation(fields: [trainerId], references: [id])
  name                     String
  phone                    String?
  birthDate                DateTime?
  sex                      String         @default("Hombre")
  heightCm                 Float          @default(175.0)
  objective                String
  status                   ClientStatus   @default(ACTIVO)
  menstrualTrackingEnabled Boolean        @default(false)
  menstrualSharedWithCoach Boolean        @default(false)
  currentMenstrualDay      Int?           @default(1)
  currentMenstrualPhase    MenstrualPhase?
  pathologiesTraining      String?
  pathologiesNutrition     String?
  sessions                 Session[]
  healthMetrics            HealthMetric[]
  biometrics               Biometric[]
  photos                   ProgressPhoto[]
  alerts                   ClientAlert[]
  trainerNotes             TrainerNote[]
  nutritionPlans           NutritionPlan[]
  createdAt                DateTime       @default(now())
  updatedAt                DateTime       @updatedAt
}

model Program {
  id              String       @id @default(uuid())
  trainerId       String
  trainer         Trainer      @relation(fields: [trainerId], references: [id])
  name            String
  type            String
  durationWeeks   Int          @default(8)
  daysPerWeek     Int          @default(4)
  level           String       @default("Intermedio")
  autoGenerated   Boolean      @default(true)
  days            ProgramDay[]
  sessions        Session[]
  createdAt       DateTime     @default(now())
}

model ProgramDay {
  id          String        @id @default(uuid())
  programId   String
  program     Program       @relation(fields: [programId], references: [id], onDelete: Cascade)
  dayNumber   Int
  title       String        // Ej: "Día 1 · Empuje"
  focusArea   String        // "Empuje", "Tirón", "Pierna", "Full body"
  exercises   Exercise[]
}

model Exercise {
  id           String        @id @default(uuid())
  programDayId String
  programDay   ProgramDay    @relation(fields: [programDayId], references: [id], onDelete: Cascade)
  name         String
  muscleGroup  String
  sets         Int           @default(4)
  reps         Int           @default(8)
  weight       String        @default("80 kg")
  rir          Int           @default(2)
  restSeconds  Int           @default(120)
  trainerTip   String?
  videoUrl     String?
  order        Int           @default(1)
}

model Session {
  id            String             @id @default(uuid())
  clientId      String
  client        Client             @relation(fields: [clientId], references: [id])
  programId     String
  program       Program            @relation(fields: [programId], references: [id])
  scheduledDate DateTime
  completedDate DateTime?
  status        String             @default("pending") // "completed", "pending", "protected_streak"
  exercisesDone SessionExercise[]
}

model SessionExercise {
  id             String    @id @default(uuid())
  sessionId      String
  session        Session   @relation(fields: [sessionId], references: [id], onDelete: Cascade)
  exerciseName   String
  setNumber      Int
  weightAchieved Float
  repsAchieved   Int
  rirRecorded    Int?
  completed      Boolean   @default(true)
}

model NutritionPlan {
  id          String     @id @default(uuid())
  clientId    String
  client      Client     @relation(fields: [clientId], references: [id])
  trainerId   String
  trainer     Trainer    @relation(fields: [trainerId], references: [id])
  objective   String
  dietType    String     @default("Omnívora")
  targetKcal  Int        @default(2200)
  proteinGrams Int       @default(160)
  carbsGrams  Int        @default(230)
  fatGrams    Int        @default(70)
  fiberGrams  Int        @default(30)
  waterLiters Float      @default(2.5)
  meals       Meal[]
  createdAt   DateTime   @default(now())
}

model Meal {
  id              String        @id @default(uuid())
  nutritionPlanId String
  nutritionPlan   NutritionPlan @relation(fields: [nutritionPlanId], references: [id], onDelete: Cascade)
  name            String        // Desayuno, Comida, Cena, Snack
  ingredientsJson String        // ["Huevos", "Avena", "Plátano"]
  completed       Boolean       @default(false)
}

model HealthMetric {
  id           String    @id @default(uuid())
  clientId     String
  client       Client    @relation(fields: [clientId], references: [id])
  metricType   String    // steps, sleep, water, kcal_burned
  value        Float
  unit         String
  recordedDate DateTime  @default(now())
}

model Biometric {
  id              String    @id @default(uuid())
  clientId        String
  client          Client    @relation(fields: [clientId], references: [id])
  weight          Float
  fatPercentage   Float?
  muscleMassKg    Float?
  waterPercentage Float?
  recordedDate    DateTime  @default(now())
}

model ProgressPhoto {
  id           String    @id @default(uuid())
  clientId     String
  client       Client    @relation(fields: [clientId], references: [id])
  angle        String    // Frontal, Lateral, Espalda
  fileUrl      String
  uploadedDate DateTime  @default(now())
}

model TrainerNote {
  id        String    @id @default(uuid())
  clientId  String
  client    Client    @relation(fields: [clientId], references: [id])
  trainerId String
  trainer   Trainer   @relation(fields: [trainerId], references: [id])
  content   String
  createdAt DateTime  @default(now())
}

model ClientAlert {
  id        String    @id @default(uuid())
  clientId  String
  client    Client    @relation(fields: [clientId], references: [id])
  alertType String    // "injury", "inactivity", "diet"
  severity  String    // "danger", "warning", "info"
  message   String
  resolved  Boolean   @default(false)
  createdAt DateTime  @default(now())
}
\`\`\`

## 3. Matriz de Endpoints REST
- POST /api/auth/login — Retorna JWT Bearer + User Profile
- GET /api/clients — Lista de clientes (filtro por estado y búsqueda)
- GET /api/clients/:id — Ficha de cliente con adherencia, patologías y métricas
- PATCH /api/clients/:id — Actualización de datos personales y seguimiento de ciclo
- POST /api/clients/:id/notes — Añadir nota del entrenador
- GET /api/programs — Programas del entrenador con clientes asignados
- POST /api/programs — Generar nuevo programa desde plantilla
- PATCH /api/programs/:id — Guardar ejercicios, series y semanas
- POST /api/sessions/:id/record-set — Registro de serie en tiempo real (peso, reps, RIR)
- GET /api/nutrition/:clientId — Plan nutricional activo y lista de la compra derivada
- POST /api/ai/query — Análisis inteligente de tendencias y alertas vía Claude
- GET /api/export — Volcado a CSV/Excel/JSON de clientes, biometría y sesiones

## 4. Reglas de Negocio Críticas
1. Privacidad del Ciclo Menstrual:
   - El cliente activa o desactiva compartir con el entrenador.
   - El entrenador NUNCA tiene acceso a fechas pasadas ni futuras de menstruación; solo lee "Fase menstrual — día X" para ajustar volumen.
2. Racha Protegida (Protected Streak):
   - Al faltar a un entrenamiento, la sesión entra en estado 'protected_streak'.
   - El cliente dispone de 7 días naturales para completarlo y salvar la racha consecutiva.
3. Lista de la compra reactiva:
   - Modificar cualquier ingrediente en las comidas del entrenador actualiza la lista de la compra del cliente inmediatamente.
`;

  const handleCopySpec = () => {
    if (navigator.clipboard) {
      navigator.clipboard.writeText(fullMarkdownSpec);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const handleDownloadSpec = () => {
    const blob = new Blob([fullMarkdownSpec], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = 'STrainer_Especificacion_Tecnica.md';
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="p-8 max-w-[1240px] mx-auto pb-24 text-[#F5F4F0]">
      {/* Top Header */}
      <div className="flex items-center justify-between pb-6 border-b border-[#2A2A2F] mb-6">
        <div>
          <span className="text-[10px] font-bold tracking-widest text-[var(--accent-color,#CFFF5C)] uppercase block mb-1">
            ARQUITECTURA Y ESPECIFICACIÓN TÉCNICA
          </span>
          <h1 className="text-2xl font-extrabold font-display text-[#F5F4F0]">
            Especificación Técnica de S-Trainer app — Plataforma de Entrenamiento
          </h1>
          <p className="text-xs text-[#8E8E94] mt-0.5">
            Garantía de implementación exacta: Esquemas de BD, Contratos API, Estados de UI y Sistema de Tokens.
          </p>
        </div>

        <div className="flex items-center gap-2.5">
          <button
            onClick={() => setShowGithubModal(true)}
            style={{ backgroundColor: 'var(--accent-color, #CFFF5C)', color: 'var(--accent-text, #101012)' }}
            className="px-5 py-2.5 rounded-full font-bold text-xs shadow-md flex items-center gap-2 transition-transform active:scale-95"
          >
            <FolderGit2 className="w-4 h-4 stroke-[2.5]" />
            <span>Subir a GitHub</span>
          </button>

          <button
            onClick={handleCopySpec}
            className="px-4 py-2.5 rounded-full bg-[#1B1B1F] border border-[#2A2A2F] text-xs font-bold text-[#F5F4F0] hover:border-[#3A3A40] flex items-center gap-2 transition-colors"
          >
            {copied ? <Check className="w-4 h-4 text-[var(--accent-color,#CFFF5C)]" /> : <Copy className="w-4 h-4" />}
            <span>{copied ? '¡Copiado!' : 'Copiar spec'}</span>
          </button>

          <button
            onClick={handleDownloadSpec}
            className="px-4 py-2.5 rounded-full bg-[#1B1B1F] border border-[#2A2A2F] text-xs font-bold text-[#F5F4F0] hover:border-[#3A3A40] flex items-center gap-2 transition-colors"
          >
            <Download className="w-4 h-4" />
            <span>Descargar .MD</span>
          </button>
        </div>
      </div>

      {/* GitHub Callout Banner */}
      <div className="p-4 rounded-[16px] bg-[#16161A] border border-[var(--accent-color,#CFFF5C)]/40 mb-6 flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div 
            className="w-9 h-9 rounded-xl flex items-center justify-center text-[#101012]"
            style={{ backgroundColor: 'var(--accent-color, #CFFF5C)' }}
          >
            <FolderGit2 className="w-4 h-4 stroke-[2.5]" />
          </div>
          <div>
            <h4 className="text-xs font-bold text-[#F5F4F0]">¿Listo para subir este código a GitHub?</h4>
            <p className="text-[11px] text-[#8E8E94]">
              El repositorio Git local está inicializado en la rama <code className="text-[#CFFF5C]">main</code> con README.md y .gitignore.
            </p>
          </div>
        </div>

        <button
          onClick={() => setShowGithubModal(true)}
          className="px-4 py-2 rounded-full bg-[#1B1B1F] border border-[#2A2A2F] text-xs font-bold text-[#F5F4F0] hover:border-[var(--accent-color,#CFFF5C)] transition-colors"
        >
          Ver comandos para tu GitHub →
        </button>
      </div>

      {/* Tabs */}
      <div className="flex items-center gap-3 mb-6 overflow-x-auto pb-2">
        {[
          { id: 'database', label: '1. Base de Datos (Prisma/SQL)', icon: Database },
          { id: 'api', label: '2. Endpoints API REST', icon: Server },
          { id: 'architecture', label: '3. Reglas & Máquinas de Estado', icon: Layers },
          { id: 'tokens', label: '4. Tokens de Diseño & Colores', icon: Palette },
          { id: 'healthkit', label: '5. Integración Apple Health', icon: Activity },
        ].map(t => {
          const Icon = t.icon;
          const isSelected = activeTab === t.id;
          return (
            <button
              key={t.id}
              onClick={() => setActiveTab(t.id as any)}
              className={`px-4 py-2.5 rounded-full text-xs font-bold flex items-center gap-2 transition-all ${
                isSelected
                  ? 'bg-[var(--accent-color,#CFFF5C)] text-[#101012] shadow-sm'
                  : 'bg-[#16161A] border border-[#2A2A2F] text-[#8E8E94] hover:text-[#F5F4F0]'
              }`}
            >
              <Icon className="w-3.5 h-3.5" />
              <span>{t.label}</span>
            </button>
          );
        })}
      </div>

      {/* Content based on tab */}
      {activeTab === 'database' && (
        <div className="space-y-4">
          <div className="p-4 rounded-[16px] bg-[#16161A] border border-[#2A2A2F]">
            <h3 className="text-sm font-bold text-[#F5F4F0] mb-2">
              Modelado de Datos Relacional Completo
            </h3>
            <p className="text-xs text-[#8E8E94] mb-4 leading-relaxed">
              Esquema normalizado para PostgreSQL compatible con Prisma ORM, Drizzle o SQLAlchemy. Incluye relaciones Trainer 1:N Clients, Client 1:N Sessions, Program 1:N Days 1:N Exercises, y tablas para métricas biométricas, impedanciometría y alertas.
            </p>
            <pre className="p-4 rounded-xl bg-[#101012] border border-[#2A2A2F] text-[11px] text-[#CFFF5C] font-mono overflow-x-auto max-h-[500px]">
{`// Prisma Schema — S-Trainer app Production Model
model Client {
  id                       String         @id @default(uuid())
  userId                   String         @unique
  trainerId                String
  name                     String
  email                    String
  phone                    String?
  birthDate                DateTime?
  sex                      String         @default("Hombre")
  heightCm                 Float          @default(175.0)
  objective                String
  status                   ClientStatus   @default(ACTIVO)
  menstrualTrackingEnabled Boolean        @default(false)
  menstrualSharedWithCoach Boolean        @default(false)
  currentMenstrualDay      Int?           @default(1)
  currentMenstrualPhase    MenstrualPhase?
  pathologiesTraining      String?
  pathologiesNutrition     String?
  sessions                 Session[]
  healthMetrics            HealthMetric[]
  biometrics               Biometric[]
  photos                   ProgressPhoto[]
  alerts                   ClientAlert[]
  trainerNotes             TrainerNote[]
  nutritionPlans           NutritionPlan[]
}

model Program {
  id            String       @id @default(uuid())
  trainerId     String
  name          String
  type          String       // Hipertrofia, Fuerza, Pérdida de grasa
  durationWeeks Int          @default(8)
  daysPerWeek   Int          @default(4)
  level         String       @default("Intermedio")
  days          ProgramDay[]
}

model ProgramDay {
  id        String     @id @default(uuid())
  programId String
  dayNumber Int
  title     String     // "Día 1 · Empuje"
  exercises Exercise[]
}

model Exercise {
  id          String   @id @default(uuid())
  name        String
  muscleGroup String
  sets        Int      @default(4)
  reps        Int      @default(8)
  weight      String   @default("80 kg")
  rir         Int      @default(2)
  restSeconds Int      @default(120)
  trainerTip  String?
}`}
            </pre>
          </div>
        </div>
      )}

      {activeTab === 'api' && (
        <div className="space-y-4">
          <div className="rounded-[16px] bg-[#16161A] border border-[#2A2A2F] overflow-hidden">
            <table className="w-full text-left text-xs border-collapse">
              <thead>
                <tr className="border-b border-[#2A2A2F] text-[10px] font-bold text-[#8E8E94] uppercase bg-[#1B1B1F]">
                  <th className="py-3 px-4">Método</th>
                  <th className="py-3 px-4">Ruta Endpoint</th>
                  <th className="py-3 px-4">Descripción Funcional</th>
                  <th className="py-3 px-4">Payload de Entrada / Respuesta</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-[#2A2A2F]/50">
                <tr>
                  <td className="py-3 px-4 font-bold text-[var(--accent-color,#CFFF5C)]">POST</td>
                  <td className="py-3 px-4 font-mono text-[#F5F4F0]">/api/auth/login</td>
                  <td className="py-3 px-4 text-[#8E8E94]">Autenticación cliente o entrenador</td>
                  <td className="py-3 px-4 text-[#8E8E94]">Email, password → Bearer token + role</td>
                </tr>
                <tr>
                  <td className="py-3 px-4 font-bold text-[#5CD6FF]">GET</td>
                  <td className="py-3 px-4 font-mono text-[#F5F4F0]">/api/clients</td>
                  <td className="py-3 px-4 text-[#8E8E94]">Lista dashboard de clientes</td>
                  <td className="py-3 px-4 text-[#8E8E94]">Query: search, status → ClientData[]</td>
                </tr>
                <tr>
                  <td className="py-3 px-4 font-bold text-[#5CD6FF]">GET</td>
                  <td className="py-3 px-4 font-mono text-[#F5F4F0]">/api/clients/:id</td>
                  <td className="py-3 px-4 text-[#8E8E94]">Ficha completa del cliente</td>
                  <td className="py-3 px-4 text-[#8E8E94]">Retorna patologías, métricas y última sesión</td>
                </tr>
                <tr>
                  <td className="py-3 px-4 font-bold text-[#FFD34D]">PATCH</td>
                  <td className="py-3 px-4 font-mono text-[#F5F4F0]">/api/clients/:id</td>
                  <td className="py-3 px-4 text-[#8E8E94]">Actualizar datos personales o ciclo</td>
                  <td className="py-3 px-4 text-[#8E8E94]">Campos editados de perfil</td>
                </tr>
                <tr>
                  <td className="py-3 px-4 font-bold text-[var(--accent-color,#CFFF5C)]">POST</td>
                  <td className="py-3 px-4 font-mono text-[#F5F4F0]">/api/sessions/:id/set</td>
                  <td className="py-3 px-4 text-[#8E8E94]">Registrar serie y abrir descanso</td>
                  <td className="py-3 px-4 text-[#8E8E94]">setNum, weight, reps, rir → triggers sync</td>
                </tr>
                <tr>
                  <td className="py-3 px-4 font-bold text-[#5CD6FF]">GET</td>
                  <td className="py-3 px-4 font-mono text-[#F5F4F0]">/api/nutrition/:clientId</td>
                  <td className="py-3 px-4 text-[#8E8E94]">Obtener plan y lista de la compra</td>
                  <td className="py-3 px-4 text-[#8E8E94]">Macros, comidas, categorías de compra</td>
                </tr>
                <tr>
                  <td className="py-3 px-4 font-bold text-[var(--accent-color,#CFFF5C)]">POST</td>
                  <td className="py-3 px-4 font-mono text-[#F5F4F0]">/api/ai/query</td>
                  <td className="py-3 px-4 text-[#8E8E94]">Consultar asistente IA (Claude)</td>
                  <td className="py-3 px-4 text-[#8E8E94]">query, clientContext → texto analítico</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      )}

      {activeTab === 'architecture' && (
        <div className="grid grid-cols-2 gap-4">
          <div className="p-5 rounded-[16px] bg-[#16161A] border border-[#2A2A2F]">
            <div className="flex items-center gap-2 mb-2 text-[var(--accent-color,#CFFF5C)] font-bold text-sm">
              <Shield className="w-4 h-4" />
              <span>Barrera de Privacidad del Ciclo</span>
            </div>
            <p className="text-xs text-[#8E8E94] leading-relaxed">
              La arquitectura de datos garantiza que el panel del entrenador <b>nunca reciba ni almacene fechas exactas de ovulación o menstruación</b>. La API mapea internamente el día del ciclo hacia una etiqueta abstracta de fase (<code className="text-[#E8A0C4]">Fase menstrual</code>, <code className="text-[#E8A0C4]">Fase lútea</code>, etc.) permitiendo ajustar volumen sin comprometer la privacidad médica.
            </p>
          </div>

          <div className="p-5 rounded-[16px] bg-[#16161A] border border-[#2A2A2F]">
            <div className="flex items-center gap-2 mb-2 text-amber-400 font-bold text-sm">
              <Layers className="w-4 h-4" />
              <span>Lógica de Racha Protegida</span>
            </div>
            <p className="text-xs text-[#8E8E94] leading-relaxed">
              Si un usuario no completa una sesión programada en su día estipulado, el estado pasa a <code className="text-amber-400">protected_streak</code> en vez de fallido. El cliente tiene una ventana de 7 días dentro de la misma semana natural para recuperar la sesión sin penalizar su conteo de semanas consecutivas.
            </p>
          </div>
        </div>
      )}

      {activeTab === 'tokens' && (
        <div className="p-5 rounded-[16px] bg-[#16161A] border border-[#2A2A2F] space-y-4">
          <h3 className="text-sm font-bold text-[#F5F4F0]">
            Tokens de Color y Jerarquía Visual
          </h3>
          <div className="grid grid-cols-3 gap-3">
            {[
              { name: 'Fondo Primario', hex: '#101012', desc: 'Canvas de la app y panel' },
              { name: 'Fondo Tarjetas', hex: '#1B1B1F', desc: 'Cards, inputs, contenedores' },
              { name: 'Bordes / Divisores', hex: '#2A2A2F', desc: 'Separadores sutiles' },
              { name: 'Texto Primario', hex: '#F5F4F0', desc: 'Titulares y datos clave' },
              { name: 'Texto Secundario', hex: '#8E8E94', desc: 'Etiquetas y metadata' },
              { name: 'Acento Lima Principal', hex: '#CFFF5C', desc: 'Color corporativo principal' },
              { name: 'Datos: Pasos', hex: '#FF6B4A', desc: 'Rojo/naranja para podometría' },
              { name: 'Datos: Peso / Medidas', hex: '#5CD6FF', desc: 'Azul cian para bioimpedancia' },
              { name: 'Datos: Sueño', hex: '#B388FF', desc: 'Púrpura dinámico' },
              { name: 'Datos: Ciclo Menstrual', hex: '#E8A0C4', desc: 'Rosa suave para fase femenina' },
            ].map((token, i) => (
              <div key={i} className="p-3 rounded-xl bg-[#1B1B1F] border border-[#2A2A2F] flex items-center gap-3">
                <div className="w-8 h-8 rounded-lg shrink-0 border border-white/10" style={{ backgroundColor: token.hex }} />
                <div>
                  <span className="text-xs font-bold text-[#F5F4F0] block leading-tight">{token.name}</span>
                  <span className="text-[10px] font-mono text-[#8E8E94]">{token.hex}</span>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {activeTab === 'healthkit' && (
        <div className="p-5 rounded-[16px] bg-[#16161A] border border-[#2A2A2F] space-y-4">
          <div className="flex items-center gap-2 text-[#5CD6FF] font-bold text-sm">
            <Smartphone className="w-4 h-4" />
            <span>Especificación de Sincronización con Apple HealthKit</span>
          </div>
          <p className="text-xs text-[#8E8E94] leading-relaxed">
            La integración lee en segundo plano las siguientes cantidades de HealthKit cada 6 horas o al abrir la app:
          </p>
          <ul className="text-xs text-[#F5F4F0] space-y-1.5 list-disc pl-5">
            <li><code>HKQuantityTypeIdentifierStepCount</code> → Mapeado a <code>metrics.stepsToday</code> (#FF6B4A)</li>
            <li><code>HKQuantityTypeIdentifierBodyMass</code> → Mapeado a <code>currentWeight</code> (#5CD6FF)</li>
            <li><code>HKCategoryTypeIdentifierSleepAnalysis</code> → Mapeado a <code>sleepHours</code> y <code>sleepQuality</code> (#B388FF)</li>
            <li><code>HKQuantityTypeIdentifierDietaryWater</code> → Mapeado a <code>waterLiters</code></li>
          </ul>
        </div>
      )}

      {/* GitHub Sync Modal */}
      <GitHubSyncModal
        isOpen={showGithubModal}
        onClose={() => setShowGithubModal(false)}
      />
    </div>
  );
};
