import test from 'node:test';
import assert from 'node:assert/strict';
import {
  buildProgramPrescriptionSnapshot,
  normalizeProgramIds,
} from '../src/lib/programVersion.mjs';
import { readFileSync } from 'node:fs';

const uuid = (n) => `00000000-0000-4000-8000-${String(n).padStart(12, '0')}`;

function sampleProgram() {
  return {
    id: 'program-a',
    name: 'Plan editable',
    assignedClientsCount: 99,
    autoGenerated: true,
    weeksVolume: [{ week: 1, volume: 90 }],
    days: [{
      id: 'd-1',
      title: 'Día 1',
      dayNumber: 1,
      focusArea: 'Fuerza',
      uiState: 'active',
      exercises: [{
        id: 'ex-1',
        name: 'Sentadilla',
        muscleGroup: 'Pierna',
        sets: 3,
        reps: 8,
        weight: '60 kg',
        rir: 2,
        restSeconds: 120,
        trainerTip: 'Controla el descenso',
        videoUrl: 'https://example.test/video',
        order: 1,
        completedCount: 2,
      }],
    }],
  };
}

test('legacy/reused IDs become UUIDs once and remain stable across later edits/reordering', () => {
  let next = 0;
  const createId = () => uuid(++next);
  const first = normalizeProgramIds(sampleProgram(), createId);
  const edited = normalizeProgramIds({
    ...first,
    days: [...first.days].reverse().map(day => ({
      ...day,
      exercises: day.exercises.map(exercise => ({ ...exercise, reps: 10 })),
    })),
  }, createId);

  assert.match(first.days[0].id, UUID_PATTERN);
  assert.match(first.days[0].exercises[0].id, UUID_PATTERN);
  assert.equal(edited.days[0].id, first.days[0].id);
  assert.equal(edited.days[0].exercises[0].id, first.days[0].exercises[0].id);

  const withNewExercise = normalizeProgramIds({
    ...edited,
    days: edited.days.map((day, index) => index === 0
      ? { ...day, exercises: [...day.exercises, { ...day.exercises[0], id: 'ex-new' }] }
      : day),
  }, createId);
  assert.notEqual(withNewExercise.days[0].exercises[1].id, withNewExercise.days[0].exercises[0].id);
  assert.match(withNewExercise.days[0].exercises[1].id, UUID_PATTERN);
});

test('version snapshot contains only the executable prescription fields', () => {
  const normalized = normalizeProgramIds(sampleProgram(), (() => {
    let n = 0;
    return () => uuid(++n);
  })());
  assert.deepEqual(buildProgramPrescriptionSnapshot(normalized), {
    schema_version: 1,
    days: [{
      id: uuid(1),
      order: 1,
      title: 'Día 1',
      focus_area: 'Fuerza',
      exercises: [{
        id: uuid(2),
        order: 1,
        name: 'Sentadilla',
        muscle_group: 'Pierna',
        target_sets: 3,
        target_reps: 8,
        target_load: '60 kg',
        target_rir: 2,
        rest_seconds: 120,
        instructions: 'Controla el descenso',
        video_url: 'https://example.test/video',
      }],
    }],
  });
});

test('empty program stays empty and does not invent a day or exercise', () => {
  assert.deepEqual(buildProgramPrescriptionSnapshot({ days: [] }), { schema_version: 1, days: [] });
});

test('saving a program waits for persistence and does not create or assign a version', () => {
  const builder = readFileSync(new URL('../src/components/trainer/TrainerProgramBuilder.tsx', import.meta.url), 'utf8');
  assert.match(builder, /await saveProgram\(normalized\)/);
  assert.match(builder, /setToast\('Cambios guardados\.'\)/);
  assert.doesNotMatch(builder, /apply_program_version|applyProgramVersion|applyProgramToClient|Guardar y asignar/);
});

const UUID_PATTERN = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
