export type AccentColor = '#CFFF5C' | '#FF6B4A' | '#5CD6FF' | '#FFD34D';

export type UserRole = 'client' | 'trainer' | 'admin';

export type ClientStatus = 'Activo' | 'Pausado' | 'Pendiente';

export type MenstrualPhase = 'Menstrual' | 'Folicular' | 'Ovulatoria' | 'Lútea';

export interface ExerciseItem {
  id: string;
  name: string;
  muscleGroup: string;
  sets: number;
  reps: number;
  weight: string;
  rir: number;
  restSeconds: number;
  trainerTip?: string;
  videoUrl?: string;
  order: number;
}

export interface ProgramDay {
  id: string;
  dayNumber: number;
  title: string; // e.g. "Día 1 · Empuje"
  focusArea: string; // "Empuje", "Tirón", "Pierna", "Full body"
  exercises: ExerciseItem[];
}

export interface ProgramWeekVolume {
  week: number;
  volume: number; // relative score / total sets
  isDeload: boolean; // descarga automática (week 4 and 8)
}

export interface Program {
  id: string;
  trainerId?: string;
  name: string;
  type: string; // Hipertrofia, Fuerza, Pérdida de grasa, Recomposición, etc.
  durationWeeks: number;
  daysPerWeek: number;
  level: string; // Principiante, Intermedio, Avanzado
  autoGenerated: boolean;
  assignedClientsCount: number;
  weeksVolume: ProgramWeekVolume[];
  days: ProgramDay[];
}

export interface ActiveProgramAssignment {
  id: string;
  client_id: string;
  program_version_id: string;
  assigned_by: string | null;
  assigned_at: string;
  ended_at: null;
  program_version: {
    id: string;
    program_id: string;
    version_number: number;
    snapshot: { schema_version: number; days: unknown[] };
    created_at: string;
  };
}

export interface TrainerProfile {
  id: string;
  name: string;
  email: string;
  initials: string;
  avatarUrl?: string;
  role: string;
  couponCode?: string;
}

export interface ClientData {
  id: string;
  trainerId?: string;
  name: string;
  initials: string;
  avatarUrl?: string;
  email: string;
  phone: string;
  birthDate: string;
  sex: 'Hombre' | 'Mujer' | 'Otro';
  height: string;
  objective: string;
  status: ClientStatus;
  nextWorkout: string;
  adherencePercentage: number;
  completedWorkoutsCount: number;
  totalScheduledWorkoutsCount: number;
  currentWeight: number;
  initialWeight: number;
  targetWeight: number;
  weightWeeklyTrend: string;
  lastCheckIn: string;
  alert?: {
    type: 'warning' | 'info' | 'danger';
    title: string;
    message: string;
    date: string;
  };
  pathologies?: {
    hasLimitations: boolean;
    training: string;
    nutrition: string;
  } | null;
  menstrualTracking: {
    enabled: boolean;
    sharedWithTrainer: boolean;
    day: number;
    phase: MenstrualPhase;
    advice: string;
  };
  metrics: {
    stepsToday: number;
    stepsGoal: number;
    kcalToday: number;
    kcalGoal: number;
    sleepHours: string;
    sleepQuality: string;
    waterLiters: number;
    waterGoal: number;
  };
  assignedProgramId: string;
  weeklySchedule: {
    day: 'L' | 'M' | 'X' | 'J' | 'V' | 'S' | 'D';
    status: 'completed' | 'pending' | 'rest' | 'protected_streak';
    dateLabel?: string;
  }[];
  strengthProgression: {
    exercise: string;
    previousWeight: number;
    currentWeight: number;
  }[];
  bodyMeasurements: {
    cintura: number;
    cadera: number;
    pecho: number;
    brazo: number;
    lastUpdated: string;
  };
  impedanceHistory: {
    date: string;
    weight: number;
    fatPercentage: number;
    muscleMassKg: number;
    waterPercentage: number;
  }[];
  trainerNotes: {
    id: string;
    date: string;
    content: string;
  }[];
}

export interface NutritionPlan {
  id: string;
  clientId: string;
  clientName: string;
  objective: string;
  dietType: 'Omnívora' | 'Vegetariana' | 'Vegana';
  targetKcal: number;
  macros: {
    protein: number; // in grams
    carbs: number;
    fat: number;
    fiber: number;
    water: number;
  };
  meals: {
    id: string;
    name: string; // Desayuno, Comida, Cena, Snack
    completed: boolean;
    ingredients: string[];
    kcalApprox: number;
  }[];
  shoppingList: {
    category: string;
    items: {
      name: string;
      checked: boolean;
    }[];
  }[];
}

export interface WorkoutSetRecord {
  setNumber: number;
  weight: number;
  reps: number;
  completed: boolean;
  rir?: number;
}

export interface WorkoutSetResult {
  id: string;
  workout_session_id: string;
  exercise_id: string;
  set_number: number;
  reps_performed: number | null;
  duration_seconds: number | null;
  load_kind: 'external_kg' | 'external_kg_per_dumbbell' | 'bodyweight' | 'none' | null;
  load_kg: number | null;
  rir_performed: number | null;
  note: string | null;
  created_at: string;
  updated_at: string;
}

export interface WorkoutSessionView {
  session: {
    id: string;
    client_program_assignment_id: string;
    program_day_id: string;
    started_at: string;
    completed_at: string | null;
  };
  program_version_id: string;
  day: ProgramDay;
  results: WorkoutSetResult[];
  recovered: boolean;
}

export interface TrainerWorkoutSnapshotExercise {
  id: string;
  order: number;
  name: string;
  muscle_group?: string | null;
  target_sets: number;
  target_reps?: number | null;
  target_load?: string | null;
  target_rir?: number | null;
  rest_seconds?: number | null;
  instructions?: string | null;
  video_url?: string | null;
}

export interface TrainerWorkoutSetResult extends WorkoutSetResult {}

export interface TrainerWorkoutHistoryEntry {
  session: WorkoutSessionView['session'];
  assignment: {
    id: string;
    client_id: string;
    program_version_id: string;
    assigned_at: string;
    ended_at: string | null;
  };
  programVersion: {
    id: string;
    program_id: string;
    version_number: number;
  };
  day: {
    id: string;
    order: number;
    title: string;
    focus_area?: string | null;
    exercises: TrainerWorkoutSnapshotExercise[];
  };
  results: TrainerWorkoutSetResult[];
}
