export type AccentColor = '#CFFF5C' | '#FF6B4A' | '#5CD6FF' | '#FFD34D';

export type UserRole = 'client' | 'trainer' | 'admin';

export type ClientStatus = 'Activo' | 'Pausado' | 'Pendiente';

export type MenstrualPhase = 'Menstrual' | 'Folicular' | 'Ovulatoria' | 'Lútea';

export interface ExerciseItem {
  id: string;
  name: string;
  muscleGroup: string;
  sets: number;
  reps: number;
  weight: string;
  rir: number;
  restSeconds: number;
  trainerTip?: string;
  videoUrl?: string;
  order: number;
}

export interface ProgramDay {
  id: string;
  dayNumber: number;
  title: string; // e.g. "Día 1 · Empuje"
  focusArea: string; // "Empuje", "Tirón", "Pierna", "Full body"
  exercises: ExerciseItem[];
}

export interface ProgramWeekVolume {
  week: number;
  volume: number; // relative score / total sets
  isDeload: boolean; // descarga automática (week 4 and 8)
}

export interface Program {
  id: string;
  name: string;
  type: string; // Hipertrofia, Fuerza, Pérdida de grasa, Recomposición, etc.
  durationWeeks: number;
  daysPerWeek: number;
  level: string; // Principiante, Intermedio, Avanzado
  autoGenerated: boolean;
  assignedClientsCount: number;
  weeksVolume: ProgramWeekVolume[];
  days: ProgramDay[];
}

export interface TrainerProfile {
  id: string;
  name: string;
  email: string;
  initials: string;
  avatarUrl?: string;
  role: string;
  couponCode?: string;
}

export interface ClientData {
  id: string;
  name: string;
  initials: string;
  avatarUrl?: string;
  email: string;
  phone: string;
  birthDate: string;
  sex: 'Hombre' | 'Mujer' | 'Otro';
  height: string;
  objective: string;
  status: ClientStatus;
  nextWorkout: string;
  adherencePercentage: number;
  completedWorkoutsCount: number;
  totalScheduledWorkoutsCount: number;
  currentWeight: number;
  initialWeight: number;
  targetWeight: number;
  weightWeeklyTrend: string;
  lastCheckIn: string;
  alert?: {
    type: 'warning' | 'info' | 'danger';
    title: string;
    message: string;
    date: string;
  };
  pathologies: {
    hasLimitations: boolean;
    training: string;
    nutrition: string;
  };
  menstrualTracking: {
    enabled: boolean;
    sharedWithTrainer: boolean;
    day: number;
    phase: MenstrualPhase;
    advice: string;
  };
  metrics: {
    stepsToday: number;
    stepsGoal: number;
    kcalToday: number;
    kcalGoal: number;
    sleepHours: string;
    sleepQuality: string;
    waterLiters: number;
    waterGoal: number;
  };
  assignedProgramId: string;
  weeklySchedule: {
    day: 'L' | 'M' | 'X' | 'J' | 'V' | 'S' | 'D';
    status: 'completed' | 'pending' | 'rest' | 'protected_streak';
    dateLabel?: string;
  }[];
  strengthProgression: {
    exercise: string;
    previousWeight: number;
    currentWeight: number;
  }[];
  bodyMeasurements: {
    cintura: number;
    cadera: number;
    pecho: number;
    brazo: number;
    lastUpdated: string;
  };
  impedanceHistory: {
    date: string;
    weight: number;
    fatPercentage: number;
    muscleMassKg: number;
    waterPercentage: number;
  }[];
  trainerNotes: {
    id: string;
    date: string;
    content: string;
  }[];
}

export interface NutritionPlan {
  id: string;
  clientId: string;
  clientName: string;
  objective: string;
  dietType: 'Omnívora' | 'Vegetariana' | 'Vegana';
  targetKcal: number;
  macros: {
    protein: number; // in grams
    carbs: number;
    fat: number;
    fiber: number;
    water: number;
  };
  meals: {
    id: string;
    name: string; // Desayuno, Comida, Cena, Snack
    completed: boolean;
    ingredients: string[];
    kcalApprox: number;
  }[];
  shoppingList: {
    category: string;
    items: {
      name: string;
      checked: boolean;
    }[];
  }[];
}

export interface WorkoutSetRecord {
  setNumber: number;
  weight: number;
  reps: number;
  completed: boolean;
  rir?: number;
}
