import { ClientData, Program, NutritionPlan } from '../types';

export const INITIAL_PROGRAMS: Program[] = [
  {
    id: 'prog-1',
    name: 'Hipertrofia — Bloque 1',
    type: 'Hipertrofia',
    durationWeeks: 8,
    daysPerWeek: 4,
    level: 'Intermedio',
    autoGenerated: true,
    assignedClientsCount: 3,
    weeksVolume: [
      { week: 1, volume: 80, isDeload: false },
      { week: 2, volume: 85, isDeload: false },
      { week: 3, volume: 90, isDeload: false },
      { week: 4, volume: 55, isDeload: true }, // descarga automática
      { week: 5, volume: 92, isDeload: false },
      { week: 6, volume: 96, isDeload: false },
      { week: 7, volume: 100, isDeload: false },
      { week: 8, volume: 60, isDeload: true }, // descarga automática
    ],
    days: [
      {
        id: 'd-1',
        dayNumber: 1,
        title: 'Día 1 · Empuje',
        focusArea: 'Empuje',
        exercises: [
          { id: 'ex-1', name: 'Press banca', muscleGroup: 'Pecho · Deltoides ant.', sets: 4, reps: 8, weight: '80 kg', rir: 2, restSeconds: 120, trainerTip: 'Pausa controlada en el pecho, sin rebotar.', order: 1 },
          { id: 'ex-2', name: 'Press militar', muscleGroup: 'Hombro', sets: 3, reps: 10, weight: '45 kg', rir: 2, restSeconds: 90, trainerTip: 'Bloquea glúteos y core en la extensión.', order: 2 },
          { id: 'ex-3', name: 'Fondos en paralelas', muscleGroup: 'Tríceps · Pecho inferior', sets: 3, reps: 12, weight: 'Peso corp.', rir: 3, restSeconds: 90, trainerTip: 'Ligera inclinación hacia delante.', order: 3 },
          { id: 'ex-4', name: 'Elevaciones laterales', muscleGroup: 'Deltoides lateral', sets: 3, reps: 15, weight: '10 kg', rir: 3, restSeconds: 60, trainerTip: 'Codos ligeramente flexionados.', order: 4 },
          { id: 'ex-5', name: 'Extensión tríceps en polea', muscleGroup: 'Tríceps', sets: 3, reps: 12, weight: '25 kg', rir: 2, restSeconds: 60, trainerTip: 'Mantén los codos pegados a los costados.', order: 5 },
        ]
      },
      {
        id: 'd-2',
        dayNumber: 2,
        title: 'Día 2 · Tirón',
        focusArea: 'Tirón',
        exercises: [
          { id: 'ex-6', name: 'Dominadas neutras', muscleGroup: 'Dorsal ancho', sets: 4, reps: 8, weight: 'Peso corp.', rir: 2, restSeconds: 120, trainerTip: 'Tracción con los dorsales hasta barbilla.', order: 1 },
          { id: 'ex-7', name: 'Remo con barra', muscleGroup: 'Espalda media', sets: 4, reps: 10, weight: '65 kg', rir: 2, restSeconds: 90, trainerTip: 'Espalda neutra en 45 grados.', order: 2 },
          { id: 'ex-8', name: 'Face pull en polea', muscleGroup: 'Deltoides post.', sets: 3, reps: 15, weight: '20 kg', rir: 3, restSeconds: 60, trainerTip: 'Lleva la cuerda a la altura de los ojos.', order: 3 },
          { id: 'ex-9', name: 'Curl bíceps con barra Z', muscleGroup: 'Bíceps', sets: 3, reps: 10, weight: '30 kg', rir: 2, restSeconds: 60, trainerTip: 'Control total en la fase excéntrica.', order: 4 },
        ]
      },
      {
        id: 'd-3',
        dayNumber: 3,
        title: 'Día 3 · Pierna',
        focusArea: 'Pierna',
        exercises: [
          { id: 'ex-10', name: 'Sentadilla', muscleGroup: 'Pierna · Cuádriceps', sets: 4, reps: 8, weight: '80 kg', rir: 2, restSeconds: 120, trainerTip: 'Tu entrenador: mejora las repeticiones de la semana pasada.', order: 1 },
          { id: 'ex-11', name: 'Peso muerto rumano', muscleGroup: 'Isquiosurales · Glúteo', sets: 4, reps: 10, weight: '85 kg', rir: 2, restSeconds: 120, trainerTip: 'Siente el estiramiento profundo.', order: 2 },
          { id: 'ex-12', name: 'Prensa inclinada', muscleGroup: 'Cuádriceps', sets: 3, reps: 12, weight: '140 kg', rir: 2, restSeconds: 90, trainerTip: 'Rango completo sin despegar la pelvis.', order: 3 },
          { id: 'ex-13', name: 'Elevación de gemelos', muscleGroup: 'Gemelos', sets: 4, reps: 15, weight: '60 kg', rir: 2, restSeconds: 60, trainerTip: 'Pausa de 2 seg en contracción máxima.', order: 4 },
        ]
      },
      {
        id: 'd-4',
        dayNumber: 4,
        title: 'Día 4 · Full body',
        focusArea: 'Full body',
        exercises: [
          { id: 'ex-14', name: 'Press inclinado mancuernas', muscleGroup: 'Pecho superior', sets: 3, reps: 10, weight: '26 kg/manc', rir: 2, restSeconds: 90, trainerTip: 'Banco a 30 grados.', order: 1 },
          { id: 'ex-15', name: 'Remo unilateral en polea', muscleGroup: 'Dorsal', sets: 3, reps: 12, weight: '35 kg', rir: 2, restSeconds: 75, trainerTip: 'Máximo estiramiento al inicio.', order: 2 },
          { id: 'ex-16', name: 'Zancadas búlgaras', muscleGroup: 'Glúteo · Cuádriceps', sets: 3, reps: 10, weight: '16 kg/manc', rir: 2, restSeconds: 90, trainerTip: 'Torso inclinado 15º.', order: 3 },
          { id: 'ex-17', name: 'Plancha abdominal', muscleGroup: 'Core', sets: 3, reps: 45, weight: 'Tiempo (s)', rir: 3, restSeconds: 60, trainerTip: 'Retroversión pélvica activa.', order: 4 },
        ]
      }
    ]
  },
  {
    id: 'prog-2',
    name: 'Pérdida de grasa — Fase 1',
    type: 'Pérdida de grasa',
    durationWeeks: 6,
    daysPerWeek: 4,
    level: 'Principiante',
    autoGenerated: true,
    assignedClientsCount: 5,
    weeksVolume: [
      { week: 1, volume: 75, isDeload: false },
      { week: 2, volume: 80, isDeload: false },
      { week: 3, volume: 85, isDeload: false },
      { week: 4, volume: 60, isDeload: true },
      { week: 5, volume: 88, isDeload: false },
      { week: 6, volume: 92, isDeload: false },
    ],
    days: [
      {
        id: 'd-21',
        dayNumber: 1,
        title: 'Día 1 · Pierna & HIIT',
        focusArea: 'Pierna',
        exercises: [
          { id: 'ex-201', name: 'Sentadilla Goblet', muscleGroup: 'Cuádriceps', sets: 4, reps: 12, weight: '24 kg', rir: 2, restSeconds: 75, order: 1 },
          { id: 'ex-202', name: 'Hip Thrust', muscleGroup: 'Glúteo', sets: 4, reps: 12, weight: '70 kg', rir: 2, restSeconds: 90, order: 2 },
        ]
      }
    ]
  },
  {
    id: 'prog-3',
    name: 'Fuerza — Powerbuilding',
    type: 'Fuerza',
    durationWeeks: 12,
    daysPerWeek: 4,
    level: 'Avanzado',
    autoGenerated: false,
    assignedClientsCount: 2,
    weeksVolume: [
      { week: 1, volume: 85, isDeload: false },
      { week: 2, volume: 90, isDeload: false },
      { week: 3, volume: 95, isDeload: false },
      { week: 4, volume: 60, isDeload: true },
      { week: 5, volume: 95, isDeload: false },
      { week: 6, volume: 100, isDeload: false },
      { week: 7, volume: 102, isDeload: false },
      { week: 8, volume: 65, isDeload: true },
    ],
    days: []
  },
  {
    id: 'prog-4',
    name: 'Recomposición — Base',
    type: 'Recomposición',
    durationWeeks: 10,
    daysPerWeek: 4,
    level: 'Intermedio',
    autoGenerated: true,
    assignedClientsCount: 1,
    weeksVolume: [
      { week: 1, volume: 80, isDeload: false },
      { week: 2, volume: 84, isDeload: false },
      { week: 3, volume: 88, isDeload: false },
      { week: 4, volume: 55, isDeload: true },
      { week: 5, volume: 90, isDeload: false },
      { week: 6, volume: 94, isDeload: false },
      { week: 7, volume: 98, isDeload: false },
      { week: 8, volume: 60, isDeload: true },
    ],
    days: []
  }
];

export const INITIAL_CLIENTS: ClientData[] = [
  {
    id: 'cli-juan',
    name: 'Juan Rodríguez',
    initials: 'JU',
    email: 'juan.rodriguez@email.com',
    phone: '+34 610 390 953',
    birthDate: '1992-06-14',
    sex: 'Hombre',
    height: '178 cm',
    objective: 'Pérdida de grasa · fuerza',
    status: 'Activo',
    nextWorkout: 'Hoy · Pierna',
    adherencePercentage: 89,
    completedWorkoutsCount: 16,
    totalScheduledWorkoutsCount: 18,
    currentWeight: 82.4,
    initialWeight: 86.0,
    targetWeight: 78.0,
    weightWeeklyTrend: '↓ 0,4 kg / semana',
    lastCheckIn: 'Hoy',
    alert: {
      type: 'danger',
      title: 'Molestia de hombro',
      message: 'Dolor reportado hace 2 días en el check-in de hombro. Revisar antes de la próxima sesión de empuje.',
      date: 'Hace 2 días'
    },
    pathologies: {
      hasLimitations: true,
      training: 'Molestia crónica de hombro derecho. Evitar press por encima de la cabeza con carga alta — priorizar press inclinado o en máquina.',
      nutrition: 'Sin restricciones alimentarias conocidas.'
    },
    menstrualTracking: {
      enabled: false,
      sharedWithTrainer: false,
      day: 0,
      phase: 'Folicular',
      advice: ''
    },
    metrics: {
      stepsToday: 8432,
      stepsGoal: 9000,
      kcalToday: 1980,
      kcalGoal: 2200,
      sleepHours: '7h 18min',
      sleepQuality: 'Calidad buena',
      waterLiters: 1.8,
      waterGoal: 2.5
    },
    assignedProgramId: 'prog-1',
    weeklySchedule: [
      { day: 'L', status: 'completed', dateLabel: 'Lunes' },
      { day: 'M', status: 'completed', dateLabel: 'Martes' },
      { day: 'X', status: 'rest', dateLabel: 'Miércoles' },
      { day: 'J', status: 'completed', dateLabel: 'Jueves' },
      { day: 'V', status: 'pending', dateLabel: 'Viernes' },
      { day: 'S', status: 'rest', dateLabel: 'Sábado' },
      { day: 'D', status: 'rest', dateLabel: 'Domingo' },
    ],
    strengthProgression: [
      { exercise: 'Press banca', previousWeight: 75, currentWeight: 80 },
      { exercise: 'Sentadilla', previousWeight: 90, currentWeight: 100 },
      { exercise: 'Peso muerto', previousWeight: 120, currentWeight: 130 },
    ],
    bodyMeasurements: {
      cintura: 84,
      cadera: 98,
      pecho: 102,
      brazo: 36,
      lastUpdated: 'Actualizadas hace 12 días'
    },
    impedanceHistory: [
      { date: 'HOY', weight: 82.4, fatPercentage: 18.2, muscleMassKg: 62.1, waterPercentage: 55 },
      { date: 'HACE 2 SEMANAS', weight: 83.8, fatPercentage: 19.0, muscleMassKg: 61.4, waterPercentage: 54 },
      { date: 'HACE 1 MES', weight: 85.2, fatPercentage: 20.3, muscleMassKg: 60.8, waterPercentage: 53.5 },
    ],
    trainerNotes: [
      {
        id: 'tn-1',
        date: 'Hace 2 días',
        content: 'Buena progresión en press banca. Vigilar molestia de hombro reportada esta semana antes de subir carga.'
      },
      {
        id: 'tn-2',
        date: 'Hace 6 días',
        content: 'Adherencia sólida este bloque. Listo para subir volumen en semana 5.'
      }
    ]
  },
  {
    id: 'cli-lucia',
    name: 'Lucía Navarro',
    initials: 'LU',
    email: 'lucia.navarro@email.com',
    phone: '+34 622 841 129',
    birthDate: '1995-11-03',
    sex: 'Mujer',
    height: '165 cm',
    objective: 'Recomposición corporal',
    status: 'Activo',
    nextWorkout: 'Hoy · Espalda',
    adherencePercentage: 73,
    completedWorkoutsCount: 11,
    totalScheduledWorkoutsCount: 15,
    currentWeight: 58.9,
    initialWeight: 60.0,
    targetWeight: 57.5,
    weightWeeklyTrend: '↓ 0,2 kg / semana',
    lastCheckIn: 'Hace 2 días',
    alert: {
      type: 'warning',
      title: 'Molestia en check-in',
      message: 'Dolor reportado hace 2 días en el check-in. Revisar en la próxima sesión.',
      date: 'Hace 2 días'
    },
    pathologies: {
      hasLimitations: false,
      training: 'Confirmado — sin restricciones de entrenamiento ni de alimentación.',
      nutrition: 'Sin restricciones de alimentación conocidas.'
    },
    menstrualTracking: {
      enabled: true,
      sharedWithTrainer: true,
      day: 3,
      phase: 'Lútea',
      advice: 'Normal si hoy rindes algo menos. Baja intensidad si lo necesitas.'
    },
    metrics: {
      stepsToday: 7150,
      stepsGoal: 8500,
      kcalToday: 1680,
      kcalGoal: 1850,
      sleepHours: '6h 40min',
      sleepQuality: 'Calidad regular',
      waterLiters: 2.1,
      waterGoal: 2.3
    },
    assignedProgramId: 'prog-4',
    weeklySchedule: [
      { day: 'L', status: 'completed', dateLabel: 'Lunes' },
      { day: 'M', status: 'rest', dateLabel: 'Martes' },
      { day: 'X', status: 'rest', dateLabel: 'Miércoles' },
      { day: 'J', status: 'completed', dateLabel: 'Jueves' },
      { day: 'V', status: 'pending', dateLabel: 'Viernes' },
      { day: 'S', status: 'rest', dateLabel: 'Sábado' },
      { day: 'D', status: 'rest', dateLabel: 'Domingo' },
    ],
    strengthProgression: [
      { exercise: 'Hip Thrust', previousWeight: 80, currentWeight: 92.5 },
      { exercise: 'Remo con barra', previousWeight: 55, currentWeight: 60 },
    ],
    bodyMeasurements: {
      cintura: 68,
      cadera: 94,
      pecho: 88,
      brazo: 28,
      lastUpdated: 'Actualizadas hace 5 días'
    },
    impedanceHistory: [
      { date: 'HOY', weight: 58.9, fatPercentage: 21.5, muscleMassKg: 42.1, waterPercentage: 57 },
      { date: 'HACE 2 SEMANAS', weight: 59.4, fatPercentage: 22.0, muscleMassKg: 41.8, waterPercentage: 56.5 },
    ],
    trainerNotes: [
      {
        id: 'tn-3',
        date: 'Hace 2 días',
        content: 'Última semana del ciclo con menos energía de lo normal — es esperable en fase lútea. Volumen ligeramente reducido esta semana.'
      },
      {
        id: 'tn-4',
        date: 'Hace 6 días',
        content: 'Buena técnica en remo. Podemos subir carga la próxima semana si se encuentra bien.'
      }
    ]
  },
  {
    id: 'cli-maria',
    name: 'María Torres',
    initials: 'MA',
    email: 'maria.torres@email.com',
    phone: '+34 633 445 566',
    birthDate: '1990-04-20',
    sex: 'Mujer',
    height: '170 cm',
    objective: 'Hipertrofia',
    status: 'Activo',
    nextWorkout: 'Mañana · Empuje',
    adherencePercentage: 95,
    completedWorkoutsCount: 19,
    totalScheduledWorkoutsCount: 20,
    currentWeight: 64.1,
    initialWeight: 62.0,
    targetWeight: 66.0,
    weightWeeklyTrend: '↑ 0,3 kg / semana',
    lastCheckIn: 'Ayer',
    pathologies: {
      hasLimitations: false,
      training: 'Sin limitaciones articulares. Excelente movilidad de tobillo y cadera.',
      nutrition: 'Tolerancia alta a carbohidratos complejos.'
    },
    menstrualTracking: {
      enabled: true,
      sharedWithTrainer: false,
      day: 12,
      phase: 'Folicular',
      advice: 'Pico de fuerza alto esta semana.'
    },
    metrics: {
      stepsToday: 10400,
      stepsGoal: 10000,
      kcalToday: 2400,
      kcalGoal: 2450,
      sleepHours: '8h 05min',
      sleepQuality: 'Óptima',
      waterLiters: 2.8,
      waterGoal: 2.8
    },
    assignedProgramId: 'prog-1',
    weeklySchedule: [
      { day: 'L', status: 'completed' },
      { day: 'M', status: 'completed' },
      { day: 'X', status: 'rest' },
      { day: 'J', status: 'completed' },
      { day: 'V', status: 'completed' },
      { day: 'S', status: 'rest' },
      { day: 'D', status: 'rest' },
    ],
    strengthProgression: [
      { exercise: 'Sentadilla', previousWeight: 80, currentWeight: 90 },
      { exercise: 'Press militar', previousWeight: 35, currentWeight: 40 },
    ],
    bodyMeasurements: { cintura: 71, cadera: 97, pecho: 92, brazo: 30, lastUpdated: 'Hace 3 días' },
    impedanceHistory: [
      { date: 'HOY', weight: 64.1, fatPercentage: 19.8, muscleMassKg: 46.8, waterPercentage: 58 }
    ],
    trainerNotes: [
      { id: 'tn-5', date: 'Ayer', content: 'Excelente adherencia (95%). Responde muy bien a la sobrecarga progresiva.' }
    ]
  },
  {
    id: 'cli-pedro',
    name: 'Pedro Gómez',
    initials: 'PE',
    email: 'pedro.gomez@email.com',
    phone: '+34 644 112 233',
    birthDate: '1988-08-11',
    sex: 'Hombre',
    height: '182 cm',
    objective: 'Fuerza',
    status: 'Pausado',
    nextWorkout: '—',
    adherencePercentage: 61,
    completedWorkoutsCount: 11,
    totalScheduledWorkoutsCount: 18,
    currentWeight: 90.2,
    initialWeight: 92.0,
    targetWeight: 88.0,
    weightWeeklyTrend: '→ 0,0 kg / semana',
    lastCheckIn: 'Hace 6 días',
    pathologies: {
      hasLimitations: true,
      training: 'Sobrecarga lumbar en peso muerto convencional. Utilizar hex bar.',
      nutrition: 'Intolerancia leve a la lactosa.'
    },
    menstrualTracking: {
      enabled: false,
      sharedWithTrainer: false,
      day: 0,
      phase: 'Folicular',
      advice: ''
    },
    metrics: {
      stepsToday: 4200,
      stepsGoal: 8000,
      kcalToday: 2100,
      kcalGoal: 2600,
      sleepHours: '6h 10min',
      sleepQuality: 'Interrumpido',
      waterLiters: 1.5,
      waterGoal: 3.0
    },
    assignedProgramId: 'prog-3',
    weeklySchedule: [
      { day: 'L', status: 'completed' },
      { day: 'M', status: 'protected_streak' },
      { day: 'X', status: 'rest' },
      { day: 'J', status: 'pending' },
      { day: 'V', status: 'pending' },
      { day: 'S', status: 'rest' },
      { day: 'D', status: 'rest' },
    ],
    strengthProgression: [
      { exercise: 'Press banca', previousWeight: 105, currentWeight: 110 }
    ],
    bodyMeasurements: { cintura: 94, cadera: 104, pecho: 112, brazo: 40, lastUpdated: 'Hace 14 días' },
    impedanceHistory: [
      { date: 'HOY', weight: 90.2, fatPercentage: 23.4, muscleMassKg: 65.2, waterPercentage: 52 }
    ],
    trainerNotes: [
      { id: 'tn-6', date: 'Hace 6 días', content: 'Viaje de trabajo durante 10 días. Plan adaptado a mancuernas en hotel.' }
    ]
  },
  {
    id: 'cli-diego',
    name: 'Diego Ferrer',
    initials: 'DI',
    email: 'diego.ferrer@email.com',
    phone: '+34 655 778 899',
    birthDate: '1998-02-14',
    sex: 'Hombre',
    height: '175 cm',
    objective: 'Pérdida de grasa',
    status: 'Pendiente',
    nextWorkout: 'Sin activar',
    adherencePercentage: 0,
    completedWorkoutsCount: 0,
    totalScheduledWorkoutsCount: 0,
    currentWeight: 88.0,
    initialWeight: 88.0,
    targetWeight: 80.0,
    weightWeeklyTrend: '—',
    lastCheckIn: '—',
    alert: {
      type: 'info',
      title: 'Invitación pendiente',
      message: 'Invitación enviada por email. Aún no ha completado el onboarding inicial.',
      date: 'Ayer'
    },
    pathologies: {
      hasLimitations: false,
      training: 'Cuestionario PAR-Q pendiente de completar en la app.',
      nutrition: 'Pendiente de valorar preferencias.'
    },
    menstrualTracking: { enabled: false, sharedWithTrainer: false, day: 0, phase: 'Folicular', advice: '' },
    metrics: { stepsToday: 0, stepsGoal: 8000, kcalToday: 0, kcalGoal: 2000, sleepHours: '—', sleepQuality: '—', waterLiters: 0, waterGoal: 2.5 },
    assignedProgramId: 'prog-2',
    weeklySchedule: [
      { day: 'L', status: 'rest' },
      { day: 'M', status: 'rest' },
      { day: 'X', status: 'rest' },
      { day: 'J', status: 'rest' },
      { day: 'V', status: 'rest' },
      { day: 'S', status: 'rest' },
      { day: 'D', status: 'rest' },
    ],
    strengthProgression: [],
    bodyMeasurements: { cintura: 92, cadera: 102, pecho: 105, brazo: 35, lastUpdated: 'Sin datos' },
    impedanceHistory: [],
    trainerNotes: [
      { id: 'tn-7', date: 'Ayer', content: 'Invitación remitida. En espera de su activación en la app.' }
    ]
  }
];

export const INITIAL_NUTRITION_PLAN: NutritionPlan = {
  id: 'nut-juan',
  clientId: 'cli-juan',
  clientName: 'Juan Rodríguez',
  objective: 'Pérdida de grasa',
  dietType: 'Omnívora',
  targetKcal: 2200,
  macros: {
    protein: 160,
    carbs: 230,
    fat: 70,
    fiber: 30,
    water: 2.5
  },
  meals: [
    {
      id: 'm-1',
      name: 'Desayuno',
      completed: true,
      ingredients: ['Huevos', 'Avena', 'Plátano', 'Almendras'],
      kcalApprox: 540
    },
    {
      id: 'm-2',
      name: 'Comida',
      completed: true,
      ingredients: ['Pechuga de pollo', 'Arroz integral', 'Espinacas', 'Aceite de oliva'],
      kcalApprox: 750
    },
    {
      id: 'm-3',
      name: 'Cena',
      completed: false,
      ingredients: ['Atún en conserva', 'Garbanzos', 'Tomate', 'Aguacate'],
      kcalApprox: 610
    },
    {
      id: 'm-4',
      name: 'Snack',
      completed: false,
      ingredients: ['Yogur natural', 'Queso fresco'],
      kcalApprox: 300
    }
  ],
  shoppingList: [
    {
      category: 'PROTEÍNAS',
      items: [
        { name: 'Pechuga de pollo', checked: true },
        { name: 'Huevos', checked: true },
        { name: 'Atún en conserva', checked: false },
        { name: 'Queso fresco', checked: false },
      ]
    },
    {
      category: 'VERDURA Y FRUTA',
      items: [
        { name: 'Aguacate', checked: true },
        { name: 'Espinacas', checked: false },
        { name: 'Tomate', checked: false },
        { name: 'Plátano', checked: true },
      ]
    },
    {
      category: 'CEREALES Y LEGUMBRES',
      items: [
        { name: 'Arroz integral', checked: true },
        { name: 'Avena', checked: false },
        { name: 'Garbanzos', checked: false },
      ]
    },
    {
      category: 'GRASAS SALUDABLES',
      items: [
        { name: 'Aceite de oliva', checked: true },
        { name: 'Almendras', checked: false },
      ]
    },
    {
      category: 'LÁCTEOS',
      items: [
        { name: 'Yogur natural', checked: false },
      ]
    }
  ]
};

export const FREQUENT_FOODS = [
  { id: 'f-1', name: 'Pechuga de pollo (150 g)', kcal: 165, protein: 31, carbs: 0, fat: 3.6 },
  { id: 'f-2', name: 'Arroz blanco (100 g cocido)', kcal: 130, protein: 2.7, carbs: 28, fat: 0.3 },
  { id: 'f-3', name: 'Huevo (unidad L)', kcal: 78, protein: 6.3, carbs: 0.4, fat: 5.3 },
  { id: 'f-4', name: 'Yogur natural (125 g)', kcal: 100, protein: 4.5, carbs: 6, fat: 3.8 },
  { id: 'f-5', name: 'Plátano (mediano 100 g)', kcal: 105, protein: 1.3, carbs: 27, fat: 0.3 },
  { id: 'f-6', name: 'Aguacate (½ unidad 80 g)', kcal: 120, protein: 1.5, carbs: 3, fat: 11 },
  { id: 'f-7', name: 'Almendras (20 g)', kcal: 116, protein: 4.2, carbs: 4.3, fat: 10 },
];
